# main task for role
- include_vars: main.yml

- name: install x11
  command: yum -y --nogpgcheck install {{ item }}
  with_items: "{{ x11 }}"

#- include: vbox_guest_add.yml

- name: "Start GUI"
  command: "{{ item }}"
  become: yes
  with_items:
    - systemctl enable gdm.service
    - systemctl set-default graphical.target
