- include_vars: main.yml
# main task for role
- name: Install common items
  yum:
    name: "{{ item }}"
    state: installed
    disable_gpg_check: yes
  with_items: "{{ common_packages }}"
  become: yes
  become_method: sudo
